# -*- coding:utf-8 -*-



MYSQL_DB_DATABASE = ''
MYSQL_DB_USER = ''
MYSQL_DB_PASSWORD = 'Sr3'
MYSQL_DB_HOST = '1200.'
MYSQL_DB_PORT = 6
MYSQL_DB_MAX_CONNECT_SIZE =2

PG_DB_DATABASE = ''
PG_DB_USER = ''
PG_DB_PASSWORD = ''
PG_DB_HOST = '1.'
PG_DB_PORT = 2
PG_DB_MAX_CONNECT_SIZE = 2

DSN = f'dbname={PG_DB_DATABASE} user={PG_DB_USER} password={PG_DB_PASSWORD} host={PG_DB_HOST} port={PG_DB_PORT}'
